html_context = {
    "display_github": True, # Integrate GitHub
    "github_user": "ElishaBentzi", # Username
    "github_repo": "E-Nation", # Repo name
    "github_version": "master", # Version
    "conf_py_path": "/docs/", # Path in the checkout to the docs root
}
